theme: jekyll-theme-console
plugins:
  - jekyll-seo-tag

title: "Mithun Roy / Ackree's Personal Portfolio"
description: "My personal website for both my engineering work and online hobbies."
baseurl: "/"
url: "https://ackreetheproot.github.io/"

header_pages:
  - index.md
  - aboutme.md
  - resume.md

style: dark

footer: 'hi chat :3'
